Лабораторна робота 1, 
студентка групи АнД-41, 
Лаврій Софія


In [1]:
import numpy as np

In [4]:
a = np.array([5])
print(a)

[5]


In [13]:
a.dtype

dtype('int32')

In [18]:
a.itemsize

4

In [9]:
len(a)

1

In [20]:
b = np.array([[1, 2, 3, 4], [9, 8, 7, 6], [5, 2, 7, 1]], dtype='float')
b

array([[1., 2., 3., 4.],
       [9., 8., 7., 6.],
       [5., 2., 7., 1.]])

In [21]:
b.shape

(3, 4)

In [33]:
b[0, 2]

3.0

In [36]:
b[1, :2]

array([9., 8.])

In [23]:
b.dtype

dtype('float64')

In [25]:
b.ndim

2

In [28]:
c = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
             [[4, 8, 2], [0, 5, 1], [8, 9, 3]],
             [[1, 0, 5], [3, 7, 2], [9, 4, 8]]], dtype='int')
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[4, 8, 2],
        [0, 5, 1],
        [8, 9, 3]],

       [[1, 0, 5],
        [3, 7, 2],
        [9, 4, 8]]])

In [29]:
c.ndim

3

In [37]:
c[0, 1, :2]

array([4, 5])

In [38]:
c[1:]

array([[[4, 8, 2],
        [0, 5, 1],
        [8, 9, 3]],

       [[1, 0, 5],
        [3, 7, 2],
        [9, 4, 8]]])

In [40]:
c[2, 1:, :2]

array([[3, 7],
       [9, 4]])

In [41]:
np.zeros((4,2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [42]:
np.ones((4,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [43]:
np.full((6), 12)

array([12, 12, 12, 12, 12, 12])

In [44]:
np.full_like(b, 4)

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [46]:
np.random.rand(2,2,3)

array([[[0.73287529, 0.95647847, 0.74085751],
        [0.21602409, 0.11098733, 0.83706431]],

       [[0.67107514, 0.93251295, 0.0947398 ],
        [0.14745826, 0.19151815, 0.73261721]]])

In [51]:
arr = np.random.randint(0,10, size=(7), dtype='int32')
arr

array([1, 5, 3, 0, 1, 8, 5])

In [48]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [49]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
r1 = np.repeat(arr,2, axis=0)
print(r1)

[1 1 5 5 3 3 0 0 1 1 8 8 5 5]


In [59]:
arr2 = np.array([[1],
                [2],
                [3]])
r2 = np.repeat(arr2, 3, axis=1)
r2

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [63]:
mas = np.zeros([5, 5])
mas

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [65]:
mas[0, 0]=5
mas

array([[5., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [66]:
tensor = np.ones((2, 4, 5))
tensor

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [68]:
tensor[1, :, 1:4] = mas[:-1, 0:3]
tensor

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 5., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.]]])

In [69]:
np.delete(b, 2, 1)

array([[1., 2., 4.],
       [9., 8., 6.],
       [5., 2., 1.]])

In [74]:
np.delete(tensor, 2, 2)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 5., 0., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.]]])